---

receivers:
 
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:55690


  # # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
  prometheus/internal:
    config:
      scrape_configs:
        - job_name: open-telemetry-collector
          scrape_interval: 30s
          static_configs:
            - targets: ['127.0.0.1:8888']

processors:
  batch:

exporters:
 
  prometheus:
    endpoint: 127.0.0.1:8004

  otlp/traces:
    endpoint: tempo:55681
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    metrics:
      receivers: [prometheus/internal]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]

